interface:

  GBG-C1_GBG-PEER1:
    state:              present
    interface:          Ethernet1/0
    description:        "DOWNLINK;ISIS-L2;LDP"
    ipam_subnet_range:  CORE
    ipam_subnet_owner:  True
    mask:               31

  BORAS-C2_GBG-C1:
    state:              present
    interface:          Ethernet1/1
    description:        "CROSSLINK;ISIS-L2;LDP"

  GBG-C1_MALMO-C1:
    state:              present
    interface:          Ethernet1/2
    description:        "UPLINK;ISIS-L2;LDP"
    ipam_subnet_range:  CORE
    ipam_subnet_owner:  True
    mask:               31

  GBG-C1_LNKPG-C1:
    state:              present
    interface:          Ethernet1/4
    description:        "UPLINK;ISIS-L2;LDP"
    ipam_subnet_range:  CORE
    ipam_subnet_owner:  True
    mask:               31

  BRLNG-C1_GBG-C1:
    state:              present
    interface:          Ethernet1/5
    description:        "UPLINK;ISIS-L2;LDP"