---

all:
  children:              
    PE:
      hosts:
        GAVLE-PE1:
          ansible_host: 100.70.6.242
        JNKPG-PE1:
          ansible_host: 100.70.6.241
        KLMR-PE1:
          ansible_host: 100.70.6.240
        KRSTD-PE1:
          ansible_host: 100.70.6.243
          
    ME:
      hosts:
        JNKPG-ME1:
          ansible_host: 100.70.6.239
        GAVLE-ME1:
          ansible_host: 100.70.6.238
        KLMR-ME1:
          ansible_host: 100.70.6.237
        KRSTD-ME1:
          ansible_host: 100.70.6.236
    
    P:
      hosts:
        BORAS-C2:
        BRLNG-C1:
        FALUN-C2:
        GBG-C1:
        NRKPG-C2:
        LNKPG-C1:
        LUND-C2:
        MALMO-C1:
        STHLM-C1:
        STHLM-C2:
        VAXJO-C2:
        VRNMO-C1:
        
    PEER:
      hosts:
        GBG-PEER1:
        MALMO-PEER1:
        STHLM-PEER1: