ansible_connection:       network_cli
ansible_user:             admin
ansible_password:         admin
ansible_network_os:       sros
ansible_ssh_common_args:  '-oKexAlgorithms=diffie-hellman-group1-sha1'