interface:
  
  LUND-C2_MALMO-PEER1:
    state:              present
    interface:          ge-0/0/1
    vlan:               0
    description:        "UPLINK;ISIS-L2;LDP"

  MALMO-C1_MALMO-PEER1:
    state:              present
    interface:          ge-0/0/0
    vlan:               0
    description:        "UPLINK;ISIS-L2;LDP"