interface:

  BORAS-C2_GBG-C1:
    state:              present
    interface:          Ethernet1/1
    description:        "CROSSLINK;ISIS-L2;LDP"
    ipam_subnet_range:   CORE
    ipam_subnet_owner:  True
    mask:               31

  BORAS-C2_GBG-PEER1:
    state:              present
    interface:          Ethernet1/0
    description:        "UPLINK;ISIS-L2;LDP"
    ipam_subnet_range:  CORE
    ipam_subnet_owner:  True
    mask:               31

  BORAS-C2_LUND-C2:
    state:              present
    interface:          Ethernet1/2
    description:        "UPLINK;ISIS-L2;LDP"
    ipam_subnet_range:  CORE
    ipam_subnet_owner:  True
    mask:               31

  BORAS-C2_FALUN-C2:
    state:              present
    interface:          Ethernet1/5
    description:        "UPLINK;ISIS-L2;LDP"
    ipam_subnet_range:  CORE
    ipam_subnet_owner:  True
    mask:               31

  BORAS-C2_NRKPG-C2:
    state:              present
    interface:          Ethernet1/4
    description:        "UPLINK;ISIS-L2;LDP"
    ipam_subnet_range:  CORE
    ipam_subnet_owner:  True
    mask:               31

  BORAS-C2_JNKPG-PE1:
    state:              present
    interface:          Ethernet1/6
    description:        "DOWNLINK;ISIS-L2;LDP"
    ipam_subnet_range:  CORE
    ipam_subnet_owner:  True
    mask:               31