---

- name: isis
  ios_config:
    src: ios_isis.j2
  register: output  
- name: changes performed
  debug:
    msg: "{{ output.commands }}"
  when: output.commands is defined


- name: isis interface
  ios_config:
    src: ios_isis_interface.j2
  when: '"ISIS" in item.value.description'
  loop: "{{ interface | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  register: output  
- name: changes performed
  debug:
    msg: "{{ output.commands }}"
  when: output.commands is defined
