bgp:
  state:    present
  as:       7
  
  vpnv4:
    
    peer_group:
      
      PEER:
        state:            present
        type:             internal
        remote_as:        7
        local_address:    "{{ interface['CORE_LOOPBACK']['ipv4'] | ipaddr('address') }}"
        cluster:          "{{ interface['CORE_LOOPBACK']['ipv4'] | ipaddr('address') }}"
        neighbor_group:
          - PEER
  
  ipv4_vrf:
    
    INTERNET:
      
      redist_connected:
        state:      present
        route_map:  RM_BGP_REDIST_CONNECTED